# Generated by Django 5.0.6 on 2024-07-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
