# Generated by Django 5.0.6 on 2024-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(choices=[(2000, '2000 USD'), (5000, '5000 USD'), (8000, '8000 USD'), (12000, '12000 USD'), (15000, '15000 USD')], default=2000),
        ),
    ]
