# Generated by Django 5.0.6 on 2024-07-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(choices=[(2000, '2000 $'), (5000, '5000 $'), (8000, '8000 $'), (12000, '12000 $'), (15000, '15000 $')], default=2000),
        ),
    ]
