# Generated by Django 5.0.6 on 2024-07-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='excerpt',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
