# Generated by Django 5.0.6 on 2024-07-17 15:05

import cloudinary.models
from django.db import migrations, models

def set_default_image(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')
    
    # Use a placeholder URL instead of uploading a new image
    placeholder_url = "https://res.cloudinary.com/your_cloud_name/image/upload/v1234567890/placeholder.jpg"
    
    # Set the placeholder URL as the image for courses without an image
    Course.objects.filter(image__isnull=True).update(image=placeholder_url)

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_excerpt'),
    ]

    operations = [
        migrations.RunPython(set_default_image),
        migrations.AlterField(
            model_name='course',
            name='excerpt',
            field=models.TextField(max_length=200, blank=False, null=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image', blank=False, null=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(max_length=3, choices=[('OW', 'Open Water'), ('AOW', 'Advanced Open Water'), ('RD', 'Rescue Diver')], blank=False, null=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(choices=[(2000, '2000 $'), (5000, '5000 $'), (8000, '8000 $'), (12000, '12000 $'), (15000, '15000 $')], default=2000, blank=False, null=False),
        ),
    ]