# Generated by Django 5.0.6 on 2024-06-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_divingcourse_booking_additional_info_booking_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divingcourse',
            name='name',
            field=models.CharField(choices=[('OW', 'Open Water'), ('AOW', 'Advanced Open Water'), ('RD', 'Rescue Diver')], max_length=3, unique=True),
        ),
    ]
