# Generated by Django 5.0.6 on 2024-07-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_rename_name_divingcourse_course_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divingcourse',
            old_name='name',
            new_name='course_type',
        ),
    ]
