# Generated by Django 5.0.6 on 2024-07-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_rename_name_divingcourse_course_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
